# prod configuration overrides
services:
  svoe_data_feed:
    image: svoe_data_feed_prod # should be synced with data_feed/ci/ scripts
    container_name: svoe_data_feed
    build:
      context: .
      dockerfile: Dockerfile
    # TODO healthcheck
    volumes:
      - ./data-feed-config.yaml:/etc/svoe/data_feed/configs/data-feed-config.yaml
    environment:
      - ENV=PROD
      - PROMETHEUS_MULTIPROC_DIR=/etc/svoe/data_feed/prometheus_multiproc_dir