apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: {{.cluster_name.value}}
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
#      additionalSecurityGroups: ["{{.k8s_security_group_id.value}}"]
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{.kops_s3_bucket_name.value}}/{{.cluster_name.value}}
  # Create one etcd member per AZ
  etcdClusters:
  – etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    – instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }}
  {{end}}
    name: main
  – etcdMembers:
  {{range $i, $az := .availability_zones.value}}
    – instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }}
  {{end}}
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.23.1
  masterPublicName: api.{{.cluster_name.value}}
  networkCIDR: {{.vpc_cidr_block.value}}
  kubeControllerManager:
    clusterCIDR: {{.vpc_cidr_block.value}}
  kubeProxy:
    clusterCIDR: {{.vpc_cidr_block.value}}
  networkID: {{.vpc_id.value}}
  kubelet:
    anonymousAuth: false
  networking:
    cilium: {}
  nonMasqueradeCIDR: {{.vpc_cidr_block.value}}
  sshAccess:
  – 0.0.0.0/0
  subnets:
  # Public (utility) subnets, one per AZ
  {{range $i, $id := .public_subnet_ids.value}}
  – id: {{.}}
    name: utility-{{index $.availability_zones.value $i}}
    type: Utility
    zone: {{index $.availability_zones.value $i}}
  {{end}}
  # Private subnets, one per AZ
  {{range $i, $id := .private_subnet_ids.value}}
  – id: {{.}}
    name: {{index $.availability_zones.value $i}}
    type: Private
    zone: {{index $.availability_zones.value $i}}
    egress: {{index $.nat_gateway_ids.value 0}}
  {{end}}
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
—

# TODO optimize rootVolumeSize
# Create one master per AZ
{{range .availability_zones.value}}
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{$.cluster_name.value}}
  name: master-{{.}}
spec:
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 20
  rootVolumeType: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{.}}
  subnets:
  – {{.}}
—
  {{end}}

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.cluster_name.value}}
  name: nodes-on-demand
spec:
  machineType: t3.small
  maxSize: 2
  minSize: 1
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-on-demand
  subnets:
  {{range .availability_zones.value}}
  – {{.}}
  {{end}}
—

# TODO set mixedInstancesPolicy
# TODO set warmPool
# TODO set maxPrice by instance type/dynamically
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.cluster_name.value}}
  name: nodes-spot
spec:
  machineType: t3.small
  maxPrice: "0.0273" # on-demand price
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-spot
  role: Node
  rootVolumeSize: 20
  rootVolumeType: gp2
  subnets:
  {{range .availability_zones.value}}
  – utility-{{.}}
  {{end}}
