site_name: SVOE
repo_url: https://github.com/anovv/svoe
repo_name: anovv/svoe
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
nav:
  - Home: index.md
  - Getting started:
      - Installation: installation.md
      - Quick start: quick-start.md
      - Architecture overview: architecture-overview.md
  - Featurizer:
      - Overview: featurizer-overview.md
      - Quick Start: featurizer-quick-start.md
      - Features and Feature Definitions: featurizer-feature-definition.md
      - Data Source Definitions: featurizer-data-source-definitions.md
      - Data Ingest: featurizer-data-ingest.md
      - Storage and Data Models: featurizer-storage.md
      - Task Graph Compilation and Execution: featurizer-task-graph.md
      - Real-time data and Streaming: featurizer-streaming.md
      - Synthetic Data Sources: featurizer-synthetic-data-sources.md
      - Configuration: featurizer-configuration.md
  - Trainer:
      - Overview: trainer-overview.md
      - Quick Start: trainer-quick-start.md
  - Backtester:
      - Overview: backtester-overview.md
      - Quick Start: backtester-quick-start.md
