site_name: Svoe
repo_url: https://github.com/dirtyValera/svoe
repo_name: dirtyValera/svoe
theme:
  name: material
nav:
  - Home: index.md
  - Getting started:
      - Installation: installation.md
      - Quick start: quick-start.md
      - Architecture overview: architecture-overview.md
  - Featurizer:
      - Overview: featurizer-overview.md
      - Quick Start: featurizer-quick-start.md
      - Features and Feature Definitions: featurizer-feature-definition.md
      - Data Source Definitions and Data Ingest: featurizer-data-source-definitions-and-data-ingest.md
      - Storage and Data Models: featurizer-storage.md
      - Task Graph Compilation and Execution: featurizer-task-graph.md
      - Real-time data and Streaming: featurizer-streaming.md
  - Trainer:
      - Overview: trainer-overview.md
  - Backtester:
      - Overview: backtester-overview.md
