apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
type: Opaque
stringData:
  thanos-objstore-config.yaml: |
    type: s3
    config:
      bucket: svoe-prometheus-thanos
      endpoint: s3.ap-northeast-1.amazonaws.com
      access_key: {{ .Values.awsKey }}
      secret_key: {{ .Values.awsSecret }}
      insecure: true