apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config-secret
type: Opaque
stringData:
  objstore.yml: |
    type: s3
    config:
      bucket: svoe-prometheus-thanos
      endpoint: s3.{{ .Values.awsRegion }}.amazonaws.com
      access_key: {{ .Values.awsKey }}
      secret_key: {{ .Values.awsSecret }}
      insecure: true