{{- $localClusterId := .Values.clusterId }}
{{- $isObserver := .Values.isObserver }}
{{ if $isObserver }}
{{- range $clusterId := .Values.clusterIds }}
{{ if not (eq $localClusterId $clusterId) }}
{{ $data := dict "clusterId" $clusterId "isObserver" $isObserver}}
{{- include "monitoring-extra.thanos-global-service" $data }}
---
{{- include "monitoring-extra.alertmanager-global-service" $data }}
---
{{ end }}
{{- end }}
{{ else }}
{{ $data := dict "clusterId" $localClusterId "isObserver" $isObserver}}
{{- include "monitoring-extra.thanos-global-service" $data }}
---
{{- include "monitoring-extra.alertmanager-global-service" $data }}
{{ end}}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  annotations:
    dns.alpha.kubernetes.io/external: prometheus.{{ .Values.clusterName }}
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-kube-prometheus-stack-prometheus-0
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  annotations:
    dns.alpha.kubernetes.io/external: grafana.{{ .Values.clusterName }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
