provider_name: cryptotick
batch_size: 12
max_executing_tasks: 10
data_source_files:
  - data_source_definition: featurizer.data_definitions.common.l2_book_incremental.cryptotick.cryptotick_l2_book_incremental.CryptotickL2BookIncrementalData
    files_and_sizes:
      - ['limitbook_full/20230201/BINANCE_SPOT_BTC_USDT.csv.gz', 252000]
      - ['limitbook_full/20230202/BINANCE_SPOT_BTC_USDT.csv.gz', 252000]
      - ['limitbook_full/20230203/BINANCE_SPOT_BTC_USDT.csv.gz', 252000]
      - ['limitbook_full/20230204/BINANCE_SPOT_BTC_USDT.csv.gz', 252000]