{% for cluster_id, pod_configs in cluster_pod_configs_mapping.items() %}
{%- raw %}{{ if eq .Values.clusterId {% endraw %}{{cluster_id}}{% raw %} }}{% endraw %}
commonSecrets:
  mysql:
    host: mysql-global-svc.mysql.svc.cluster.local # namespace should be synced with mysql chart
    port: 3306
    database: {%- raw %} {{ .Values | get "mysqlDefaultSvoeDb" }}{% endraw %}
    user: root # TODO
    password: {%- raw %} {{ .Values | get "mysqlRootPassword" }}{% endraw %}
  s3:
    accessKeyId: {%- raw %} {{ .Values | get "awsKey" }}{% endraw %}
    secretAccessKey: {%- raw %} {{ .Values | get "awsSecret" }}{% endraw %}
    region: {%- raw %} {{ .Values | get "awsDefaultRegion" }}{% endraw %}
podConfigs:
  {%- for pod_config in pod_configs %}
  - name: {{ pod_config['name'] }}
    exchange: {{ pod_config['exchange'] }}
    instrumentType: {{ pod_config['instrument_type'] }}
    {%- if pod_config['instrument_extra'] is defined %}
    instrumentExtra:
      strikePrice: {{ pod_config['instrument_extra']['strike_price'] }}
      expirationDate: {{ pod_config['instrument_extra']['expiration_date'] }}
    {%- endif %}
    launchOnDeploy: {{ pod_config['launch_on_deploy'] }}
    symbols:
      {%- for symbol in pod_config['symbols'] %}
      - symbol: {{ symbol['symbol'] }}
        base: {{ symbol['base'] }}
        quote: {{ symbol['quote'] }}
      {%- endfor %}
    labels:
      {%- for key in pod_config['labels'] %}
      {{ key }}: {{ pod_config['labels'][key] }}
      {%- endfor %}
    redis:
      port: {{ pod_config['redis_port'] }}
    dataFeed:
      {% raw %}{{ if eq .Values.clusterType "minikube" }}{% endraw %}
      imagePullSecret: regcred
      {% raw %}{{ end }}{% endraw %}
      healthPath: {{ pod_config['data_feed_health_path'] }}
      healthPort: {{ pod_config['data_feed_health_port'] }}
      prometheus:
        metricsPort: {{ pod_config['prometheus_metrics_port'] }}
        multiprocDir: {{ pod_config['prometheus_multiproc_dir'] }}
      {%- if pod_config['data_feed_resources'] is defined %}
      resources:
        {%- if pod_config['data_feed_resources']['data-feed-container'] is defined %}
        dataFeedContainer:
          {%- if pod_config['data_feed_resources']['data-feed-container']['requests'] is defined %}
          requests:
            {%- if pod_config['data_feed_resources']['data-feed-container']['requests']['cpu'] is defined %}
            cpu: {{ pod_config['data_feed_resources']['data-feed-container']['requests']['cpu'] }}
            {%- endif %}
            {%- if pod_config['data_feed_resources']['data-feed-container']['requests']['memory'] is defined %}
            memory: {{ pod_config['data_feed_resources']['data-feed-container']['requests']['memory'] }}
            {%- endif %}
          {%- endif %}
          {%- if pod_config['data_feed_resources']['data-feed-container']['limits'] is defined %}
          limits:
            {%- if pod_config['data_feed_resources']['data-feed-container']['limits']['cpu'] is defined %}
            cpu: {{ pod_config['data_feed_resources']['data-feed-container']['limits']['cpu'] }}
            {%- endif %}
            {%- if pod_config['data_feed_resources']['data-feed-container']['limits']['memory'] is defined %}
            memory: {{ pod_config['data_feed_resources']['data-feed-container']['limits']['memory'] }}
            {%- endif %}
          {%- endif %}
        {%- endif %}
        {%- if pod_config['data_feed_resources']['redis'] is defined %}
        redis:
          {%- if pod_config['data_feed_resources']['redis']['requests'] is defined %}
          requests:
            {%- if pod_config['data_feed_resources']['redis']['requests']['cpu'] is defined %}
            cpu: {{ pod_config['data_feed_resources']['redis']['requests']['cpu'] }}
            {%- endif %}
            {%- if pod_config['data_feed_resources']['redis']['requests']['memory'] is defined %}
            memory: {{ pod_config['data_feed_resources']['redis' ]['requests']['memory'] }}
            {%- endif %}
          {%- endif %}
          {%- if pod_config['data_feed_resources']['redis']['limits'] is defined %}
          limits:
            {%- if pod_config['data_feed_resources']['redis']['limits']['cpu'] is defined %}
            cpu: {{ pod_config['data_feed_resources']['redis']['limits']['cpu'] }}
            {%- endif %}
            {%- if pod_config['data_feed_resources']['redis']['limits']['memory'] is defined %}
            memory: {{ pod_config['data_feed_resources']['redis']['limits']['memory'] }}
            {%- endif %}
          {%- endif %}
        {%- endif %}
        {%- if pod_config['data_feed_resources']['redis-exporter'] is defined %}
        redisExporter:
          {%- if pod_config['data_feed_resources']['redis-exporter']['requests'] is defined %}
          requests:
            {%- if pod_config['data_feed_resources']['redis-exporter']['requests']['cpu'] is defined %}
            cpu: {{ pod_config['data_feed_resources']['redis-exporter']['requests']['cpu'] }}
            {%- endif %}
            {%- if pod_config['data_feed_resources']['redis-exporter']['requests']['memory'] is defined %}
            memory: {{ pod_config['data_feed_resources']['redis-exporter']['requests']['memory'] }}
            {%- endif %}
          {%- endif %}
          {%- if pod_config['data_feed_resources']['redis-exporter']['limits'] is defined %}
          limits:
            {%- if pod_config['data_feed_resources']['redis-exporter']['limits']['cpu'] is defined %}
            cpu: {{ pod_config['data_feed_resources']['redis-exporter']['limits']['cpu'] }}
            {%- endif %}
            {%- if pod_config['data_feed_resources']['redis-exporter']['limits']['memory'] is defined %}
            memory: {{ pod_config['data_feed_resources']['redis-exporter']['limits']['memory'] }}
            {%- endif %}
          {%- endif %}
        {%- endif %}
      {%- endif %}
      image: {%- raw %} {{ .Values.dataFeedImagePrefix }}:v{% endraw %}{{ pod_config['data_feed_image_version'] }}
      configVolumeMountPath: /etc/svoe/data_feed/configs
      config: |
        {{ pod_config['data_feed_config'] | indent(width=8) }}
  {%- endfor %}
{% raw %}{{ end }}{% endraw %}
{% endfor %}
