apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
{{ include "ray-cluster.labels" . | indent 4 }}
  name: {{ include "ray-cluster.fullname" . }}
  {{ if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
  {{ end }}
spec:
  {{- if .Values.head.rayVersion }}
  rayVersion: {{ .Values.head.rayVersion }}
  {{- end }}
  {{- if .Values.head.enableInTreeAutoscaling }}
  enableInTreeAutoscaling: {{ .Values.head.enableInTreeAutoscaling }}
  {{- end }}
  {{- if .Values.head.autoscalerOptions }}
  autoscalerOptions: {{- toYaml .Values.head.autoscalerOptions | nindent 4 }}
  {{- end }}
  headGroupSpec:
    serviceType: {{ .Values.service.type }}
    rayStartParams:
    {{- if and (not .Values.head.rayStartParams) (not .Values.head.initArgs) }}
      {}
    {{- else }}
      {{- range $key, $val := .Values.head.rayStartParams }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- /*
      initArgs is a deprecated alias for rayStartParams.
      */}}
      {{- range $key, $val := .Values.head.initArgs }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
    template:
      spec:
        imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 10 }}
        {{- if .Values.head.serviceAccountName }}
        serviceAccountName: {{ .Values.head.serviceAccountName }}
        {{- end }}
        containers:
          - volumeMounts: {{- toYaml .Values.head.volumeMounts | nindent 12 }}
            name: ray-head
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources: {{- toYaml .Values.head.resources | nindent 14 }}
            securityContext:
            {{- toYaml .Values.head.securityContext | nindent 14 }}
            env:
            {{- toYaml .Values.head.containerEnv | nindent 14}}
            {{- with .Values.head.envFrom }}
            envFrom: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- if .Values.head.ports }}
            ports: {{- toYaml .Values.head.ports | nindent 14}}
            {{- end }}
            {{- if .Values.head.lifecycle }}
            lifecycle:
            {{- toYaml .Values.head.lifecycle | nindent 14 }}
            {{- end }}
            {{- if .Values.head.command }}
            command: {{- toYaml .Values.head.command | nindent 14}}
            {{- end }}
            {{- if .Values.head.args }}
            args: {{- toYaml .Values.head.args | nindent 14}}
            {{- end }}
          {{- if .Values.head.sidecarContainers }}
          {{- toYaml .Values.head.sidecarContainers | nindent 10 }}
          {{- end }}
        volumes: {{- toYaml .Values.head.volumes | nindent 10 }}
        affinity: {{- toYaml .Values.head.affinity | nindent 10 }}
        tolerations: {{- toYaml .Values.head.tolerations | nindent 10 }}
        nodeSelector: {{- toYaml .Values.head.nodeSelector | nindent 10 }}
      metadata:
        annotations: {{- toYaml .Values.head.annotations | nindent 10 }}
        {{- if .Values.head.labels }}
        labels: {{- toYaml .Values.head.labels | nindent 10 }}
{{ include "ray-cluster.labels" . | indent 10 }}
        {{ else }}
        labels: {{ include "ray-cluster.labels" . | nindent 10 }}
        {{- end }} 

  workerGroupSpecs:
  {{- range $groupName, $values := .Values.additionalWorkerGroups }}
  {{- if ne $values.disabled true }}
  - rayStartParams:
    {{- if and (not $values.rayStartParams) (not $values.initArgs) }}
      {}
    {{- else }}
      {{- range $key, $val := $values.rayStartParams }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- /*
      initArgs is a deprecated alias for rayStartParams.
      */}}
      {{- range $key, $val := $values.initArgs }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
    replicas: {{ $values.replicas }}
    minReplicas: {{ $values.minReplicas | default (default 1 $values.miniReplicas) }}
    maxReplicas: {{ $values.maxReplicas | default (default 2147483647 $values.maxiReplicas) }}
    groupName: {{ $groupName }}
    template:
      spec:
        imagePullSecrets: {{- toYaml $.Values.imagePullSecrets | nindent 10 }}
        {{- if $values.serviceAccountName }}
        serviceAccountName: {{ $values.serviceAccountName }}
        {{- end }}
        containers:
          - volumeMounts: {{- toYaml $values.volumeMounts | nindent 12 }}
            name: ray-worker
            image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            resources: {{- toYaml $values.resources | nindent 14 }}
            securityContext:
            {{- toYaml $values.securityContext | nindent 14 }}
            env:
            {{- toYaml $values.containerEnv | nindent 14}}
            {{- if $values.envFrom }}
            envFrom: {{- toYaml $values.envFrom | nindent 14}}
            {{- end }}
            ports: {{- toYaml $values.ports | nindent 14}}
            {{- if $values.lifecycle }}
            lifecycle:
            {{- toYaml $values.lifecycle | nindent 14 }}
            {{- end }}
            {{- if $values.command }}
            command: {{- toYaml $values.command | nindent 14}}
            {{- end }}
            {{- if $values.args }}
            args: {{- toYaml $values.args | nindent 14}}
            {{- end }}
          {{- if $values.sidecarContainers }}
          {{- toYaml $values.sidecarContainers | nindent 10 }}
          {{- end }}
        volumes: {{- toYaml $values.volumes | nindent 10 }}
        affinity: {{- toYaml $values.affinity | nindent 10 }}
        tolerations: {{- toYaml $values.tolerations | nindent 10 }}
        nodeSelector: {{- toYaml $values.nodeSelector | nindent 10 }}
      metadata:
        annotations: {{- toYaml $values.annotations | nindent 10 }}
        {{- if $values.labels }}
        labels: {{- toYaml $values.labels | nindent 10 }}
{{ include "ray-cluster.labels" $ | indent 10 }}
        {{ else }}
        labels: {{ include "ray-cluster.labels" $ | nindent 10 }}
        {{- end }} 

  {{- end }}
  {{- end }}
  {{- if ne (.Values.worker.disabled | default false) true }}
  - rayStartParams:
    {{- if and (not .Values.worker.rayStartParams) (not .Values.worker.initArgs) }}
      {}
    {{- else }}
      {{- range $key, $val := .Values.worker.rayStartParams }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- /*
      initArgs is a deprecated alias for rayStartParams.
      */}}
      {{- range $key, $val := .Values.worker.initArgs }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
    replicas: {{ .Values.worker.replicas }}
    minReplicas: {{ .Values.worker.minReplicas | default (default 1 .Values.worker.miniReplicas) }}
    maxReplicas: {{ .Values.worker.maxReplicas | default (default 2147483647 .Values.worker.maxiReplicas) }}
    groupName: {{ .Values.worker.groupName }}
    template:
      spec:
        imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 10 }}
        {{- if .Values.worker.serviceAccountName }}
        serviceAccountName: {{ .Values.worker.serviceAccountName }}
        {{- end }}
        containers:
          - volumeMounts: {{- toYaml .Values.worker.volumeMounts | nindent 12 }}
            name: ray-worker
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources: {{- toYaml .Values.worker.resources | nindent 14 }}
            securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 14 }}
            env:
            {{- toYaml .Values.worker.containerEnv | nindent 14}}
            {{- with .Values.worker.envFrom }}
            envFrom: {{- toYaml . | nindent 14}}
            {{- end }}
            ports: {{- toYaml .Values.worker.ports | nindent 14}}
            {{- if .Values.worker.lifecycle }}
            lifecycle:
            {{- toYaml .Values.worker.lifecycle | nindent 14 }}
            {{- end }}
            {{- if .Values.worker.command }}
            command: {{- toYaml .Values.worker.command | nindent 14}}
            {{- end }}
            {{- if .Values.worker.args }}
            args: {{- toYaml .Values.worker.args | nindent 14}}
            {{- end }}
          {{- if .Values.worker.sidecarContainers }}
          {{- toYaml .Values.worker.sidecarContainers | nindent 10 }}
          {{- end }}
        volumes: {{- toYaml .Values.worker.volumes | nindent 10 }}
        affinity: {{- toYaml .Values.worker.affinity | nindent 10 }}
        tolerations: {{- toYaml .Values.worker.tolerations | nindent 10 }}
        nodeSelector: {{- toYaml .Values.worker.nodeSelector | nindent 10 }}
      metadata:
        annotations: {{- toYaml .Values.worker.annotations | nindent 10 }}
        {{- if .Values.worker.labels }}
        labels: {{- toYaml .Values.worker.labels | nindent 10 }}
{{ include "ray-cluster.labels" . | indent 10 }}
        {{ else }}
        labels: {{ include "ray-cluster.labels" $ | nindent 10 }}
        {{- end }}
  {{- end }}
