cache: redis
exchanges:
  BINANCE:
    l2_book:
      book_delta: true
      max_depth: 100
      symbols: &id001
      - BTC-USDT
    retries: -1
    ticker: *id001
    trades: *id001
  BYBIT:
    funding: &id002
    - BTC-USDT-PERP
    l2_book:
      book_delta: true
      max_depth: 100
      symbols: *id002
    liquidations: *id002
    open_interest: *id002
    retries: -1
    trades: *id002
  KRAKEN:
    l2_book:
      book_delta: true
      max_depth: 100
      symbols: &id003
      - BTC-USDT
    retries: -1
    ticker: *id003
    trades: *id003
health_check:
  path: /health
  port: 1234
num_write_threads: 100
prometheus:
  multiproc_dir: /etc/svoe/data_feed/prometheus_multiproc_dir
  port: 8000
redis:
  del_after_read: true
  ip: redis
  port: 6379
  retention_time: null
  socket: null
  start_flush: true
storage:
- svoe
storage_interval: 60
storage_retries: 3
storage_retry_wait: 10
svoe:
  compression: gzip
  glue_database: svoe_glue_db
  s3_bucket: svoe.test.1
  s3_prefix: data_lake
  instrument_type: spot
  version: local
write_on_stop: true
