version: "3.9"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    command: [ "redis-server", "--save", "''", "--appendonly", "no" ]
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-db:/var/lib/mysql
      - ../helm/charts/local/mysql-extra/scripts/mysqls3init.sh:/scripts/mysqls3init.sh
      - ../helm/charts/local/mysql-extra/scripts/mysqls3restore.sh:/scripts/mysqls3restore.sh
    env_file:
      - ./secrets_DO_NOT_COMMIT.env
  svoe_data_feed:
    build:
      context: .
      dockerfile: Doockerfile # dev
    volumes:
      - ./data-feed-config.yaml:/etc/svoe/data_feed/configs/data-feed-config.yaml
      - ../../cryptofeed:/etc/svoe/local_packages/cryptofeed # mounts local python project to use instead of pip packages
      - ../../cryptostore:/etc/svoe/local_packages/cryptostore
    env_file:
      - ./secrets_DO_NOT_COMMIT.env
  dumper:
    image: alpine:latest
    restart: always
    volumes:
      - ../helm/charts/local/mysql-extra/scripts/mysqls3init.sh:/scripts/mysqls3init.sh
      - ../helm/charts/local/mysql-extra/scripts/mysqls3dump.sh:/scripts/mysqls3dump.sh
    env_file:
      - ./secrets_DO_NOT_COMMIT.env
volumes:
  mysql-db: