# prod configuration overrides
services:
  svoe_data_feed:
    image: svoe_data_feed_prod
    build:
      context: .
      dockerfile: Dockerfile
    # TODO healthcheck
    volumes:
      - ./data-feed-config.yaml:/etc/svoe/data_feed/configs/data-feed-config.yaml
    environment:
      - ENV=PROD
    depends_on:
      - mysql
      - redis
    ports:
      - 1234:1234
      - 8000:8000
    expose:
      - 1234
      - 8000