version: "3.9"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    command: [ "redis-server", "--save", "''", "--appendonly", "no" ]
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-db:/var/lib/mysql
      # https://iamvickyav.medium.com/mysql-init-script-on-docker-compose-e53677102e48
    environment:
      # TODO figure out why this password is not set/working
      - MYSQL_ROOT_PASSWORD=root # should be in sync with secrets_DO_NOT_COMMIT.env
    # TODO depends_on dumper-restorer for correct shutdown sequence and dump?
  svoe_data_feed:
    image: svoe_data_feed_dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    # TODO healthcheck
    volumes:
      - ./data-feed-config.yaml:/etc/svoe/data_feed/configs/data-feed-config.yaml
      - ../../cryptofeed:/etc/svoe/local_packages/cryptofeed # mounts local python project to use instead of pip packages
      - ../../cryptostore:/etc/svoe/local_packages/cryptostore
    env_file:
      - ./secrets_DO_NOT_COMMIT.env
    environment:
      - ENV=DEV
    depends_on:
      - mysql
      - redis
  dumper-restorer:
    # TODO add on-destroy hook and launch dump script
    command: sh -c "/scripts/mysqls3init.sh; /scripts/mysqls3restore.sh; while true; do echo 'Sleeping 30s...' && sleep 30; done;"
    image: alpine:latest
    restart: always
    volumes:
      - ../helm/charts/local/mysql-extra/scripts/mysqls3init.sh:/scripts/mysqls3init.sh
      - ../helm/charts/local/mysql-extra/scripts/mysqls3restore.sh:/scripts/mysqls3restore.sh
      - ../helm/charts/local/mysql-extra/scripts/mysqls3dump.sh:/scripts/mysqls3dump.sh
    env_file:
      - ./secrets_DO_NOT_COMMIT.env
volumes:
  mysql-db: