{{ if .Values.isMysqlHost }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqls3backup-cm # should be in sync with mysql dumper sidecar
  namespace: {{ .Release.Namespace }}
data:
  mysqls3init.sh: |-
{{ .Files.Get "scripts/mysqls3init.sh" | indent 4 }}
  mysqls3restore.sh: |-
{{ .Files.Get "scripts/mysqls3restore.sh" | indent 4 }}
  mysqls3dump.sh: |-
{{ .Files.Get "scripts/mysqls3dump.sh" | indent 4 }}
{{ end }}