{{ if .Values.isMysqlHost }}
apiVersion: v1
kind: Secret
metadata:
  name: mysqls3backup-secret # should be synced with mysql chart
type: Opaque
stringData:
  MYSQL_HOST: {{ .Values.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  AWS_S3_MYSQL_BUCKET: {{ .Values.s3.mysqlBucket | quote }}
  AWS_REGION: {{ .Values.s3.region | quote }}
  CLUSTER_NAME: {{ .Values.clusterName | quote }}
{{ end }}