{{ if .Values.isMysqlHost }}
apiVersion: v1
kind: Secret
metadata:
  name: mysqls3backup-secret # should be synced with mysql chart
type: Opaque
data:
  MYSQL_HOST: {{ .Values.mysql.host }}
  MYSQL_PORT: {{ .Values.mysql.port }}
  MYSQL_DATABSE: {{ .Values.mysql.database }}
  MYSQL_USER: {{ .Values.mysql.user}}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey }}
  AWS_S3_BUCKET: {{ .Values.s3.bucket }}
  AWS_REGION: {{ .Values.s3.region }}
{{ end }}