apiVersion: v1
kind: Service
metadata:
  name: mysql-global-svc
  annotations:
    io.cilium/global-service: "true"
spec:
  type: ExternalName # TODO ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  {{ if .Values.isMysqlHost }}
  externalName: mysql.mysql.svc.cluster.local
# TODO if using ClusterIP use selector
#  selector:
#    app.kubernetes.io/component: primary
# TODO add other labels (common.labels)
  {{ end }}