quote: &id001
  exchange: 'BINANCE'
  instrument_type: 'spot'
  asset: 'USDT'
wallets:
  - asset_instrument: *id001
    balance: 10000
  - asset_instrument:
      exchange: 'BINANCE'
      instrument_type: 'spot'
      asset: 'BTC'
    balance: 0