apiVersion: v1
kind: Secret
metadata:
  name: ray-mysql-secret
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_HOST: {{ .Values.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ray-aws-creds-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.s3.region | quote }}