awsKey: ENC[AES256_GCM,data:MG/dLw7cdTmOQRVQDjGCsom8n/w=,iv:U1QrVSaHhjKcG24kJuEbyJoWbfd3/SbfB4GGKwyOuJ0=,tag:xdMyMRD218Dw+hloheer3A==,type:str]
awsSecret: ENC[AES256_GCM,data:OxVXQMZqQZrOmG+gl/nyFA2dGLPfvI5CmaUR+jp5pUy1BGbEsI5g7w==,iv:yITiFn94I7aRVhNuT/sKFoZKdk6dX0lfw0OPekVNlzE=,tag:FAG12jknbhBP1jApmxrCrA==,type:str]
awsDefaultRegion: ENC[AES256_GCM,data:W18rlsaTGWVOSJWhPCA=,iv:YvxC0jVUNpB91O8vZAhJ/YiW7Fxdi1khaEZOU0KCAFE=,tag:byPJVd23fmxldZLBHE/pPw==,type:str]
minioRootUser: ENC[AES256_GCM,data:Xp9IpuQ=,iv:7JYYFGKt0KjcbuF7O0bm/myJNBnAo8x9wYTpJ6KKpDY=,tag:W474HAVw8Vf6ye8Af4zulw==,type:str]
minioRootPassword: ENC[AES256_GCM,data:E8W8lP0Kkl7zsG4=,iv:EYPsorhk9xar/MjkEVGsamitJ6QFQZYXwlkGEvpXs5U=,tag:uDZ37wNmKn+pK2qWhXugOw==,type:str]
grafanaAdminPassword: ENC[AES256_GCM,data:EE+A1Z5v7hAzT5Pflg==,iv:R+uZUJnM8LJ8xIioYWyymQewBKB6I72lQYgl9zbdhG8=,tag:qqzNSQ3wnQijdgS+CYqmkw==,type:str]
mysqlRootPassword: ENC[AES256_GCM,data:ZI0QhuipBxfNuS0=,iv:W0ZJoQPVsVRug4bdGmGT/Uy7feY9hpR8WXAxZQNBhFA=,tag:nBfq8DXMRZhqrDVNOF1Cuw==,type:str]
mysqlDefaultSvoeDb: ENC[AES256_GCM,data:TtPRlEhcfQ==,iv:lFuoBf2iGJzThj1xKf1ziQvt3TrULavLuEtw+IQxgp4=,tag:4vQD2ifKoopZXaSUTuuPrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1krdwnh00t6u9ldsemglfg9wdvjuhws4zq67c596uf2tafzy0h5jsnk9rwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaERIZUpHdi8rTjA2UzMw
            bkRzMVNGNCtaUzFBLzd3T3VFVnI2M3laZm1zCnA2dHcySjl4Ly9Vc09YWngxNUVR
            K1RnVXB5UDhXc3RKVU10TGE3SGJxQmcKLS0tIDAvUmczL0dKWnNCVDZmb0IxaGx6
            QUtGN00zZHRjQ0VCYzhXbFNBUmlROVUKvehXA64IeA/n8ELLmeYuFQfBNUUvZ5/s
            4ZkDPDhTEu7Y0KPjaMu9F9XNbi9MjNiBfhdRN5WCnCnt9AnF0SIvZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-10T14:24:25Z"
    mac: ENC[AES256_GCM,data:m3zbrhL978reyenD9xOn7ujC8iHTy957a/ZSVCILcDmvG/paEKSFm7eLLirXHA8uB19nCt8q58wc0fSsVpLMInCrsx915xmv4NeGogp4paApElQi4jtAfqoIQfwIiMvq33bJpnTY1F1lKPqG5JP4qYLxN8RK6J+LtEEEetQTs1w=,iv:HhjMRh350KhD9xLH4mFHdg6QVq3QooRjxPIpyN3O2hg=,tag:/CIXirA7jFo3NmrRiPmdVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
