awsKey: ENC[AES256_GCM,data:cQ7pXPsywwjf,iv:CA/cKN+ZM3Wj3M44lEr9R+D/wAfv0/hIZVUO+4ORXT8=,tag:/+PDpG0AARdLmi6Y2rBFzA==,type:str]
awsSecret: ENC[AES256_GCM,data:BMlNfygmkL/SvfXD,iv:+lhvb4SRtJjl0r1O+eB7GFowtKJT4rVJcbNsnOo03Ck=,tag:bQXJG4yKujhhaiIZoOFxgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1krdwnh00t6u9ldsemglfg9wdvjuhws4zq67c596uf2tafzy0h5jsnk9rwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNStzUmQ0WDdZVkpZRExG
            WG90WlR1UG1aOUV5NFJLSFJyZUdLbFNaOUgwCnFuOWZsZUxBZWdCMDEzRGVGZ0hP
            S2ZMcGIxU2VTOVlUVHI5VlZRR096aXcKLS0tIGNWMFBYUGxBWjVLdmw2ZUtkY3BG
            VmhEVU5xa2MwamhURXd0dFE0N0d3SjQKDXWVOKM/6Cl0zujWFgNBCOAHNBGmRYWv
            cR740ZOS3YEPr9ci5t0KYuWmxWbtEsl4C40qNW+Bq56XBAfUWcwFpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-17T07:08:29Z"
    mac: ENC[AES256_GCM,data:PdXaWoRy9H9/zTbNgU6veKO3PQlElis/Slc6xJlJl/krm+fOTUWFD7/KxZjqNE+LqklGA8qZO0LMxAhLUHCcapzgpmBiks3gtVPx+ooNWnds0Iu6xO64Clp4aO/dQUftHBHWDLIqHHI+3ZCRB2jSaVcpppXOfIOrxTdOZjSC4rU=,iv:N7vVFzWcorlK53KJ8x/kiUTPYaAQsvSGp4mu8EocOI0=,tag:sBRbBomqeDhIqCH2nEKarw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
