awsKey: ENC[AES256_GCM,data:WBG43KuKD6DvyG8plt1hHP95Jj0=,iv:U9o5V2ikEZ8jpsV9zs3B/HBziImErUZvpOH6xN9rEAs=,tag:xsC8qCqFB6cClJOvPVLN1Q==,type:str]
awsSecret: ENC[AES256_GCM,data:fGdjv6l0OWqrc0xcWN4YTzw9lSxcWGRtxZ7tDr955nmrnuYyrjCrNQ==,iv:pKwkHK9V4KzbihG8bDE+7MFwzYEUyJpqzRXn4esw+kE=,tag:RYyTNFhJxt/09j73FeZ4ag==,type:str]
awsDefaultRegion: ENC[AES256_GCM,data:EimCezRUoXIzvbR1kuM=,iv:q3WnQeH7esEHOQntlx9IyeTxF/R1+ew6Yu/XMoUuo0A=,tag:lhW7EFr2B3KK+UN7vO2Vdg==,type:str]
minioRootUser: ENC[AES256_GCM,data:JNYzTE0=,iv:hylTiAJv2Bi8IOnDgNl3yP5VQn9vdISv15PSN/YtFlA=,tag:aJyOvRY59KFidoDaSQaVyA==,type:str]
minioRootPassword: ENC[AES256_GCM,data:MnTPqq9IigRBCrw=,iv:b9/sFjXmUEdHCxCTfVtEGlWIn/65pQyldipzZaQyjno=,tag:GHSpKQOs3xY6zjtecO1Ybg==,type:str]
grafanaAdminPassword: ENC[AES256_GCM,data:Fz9Tv3O5l0Zej2/xhA==,iv:up/8YCrh/TMljuj5k43a6hFEudp6KtAyQ+H9hb7eDdA=,tag:9+8ZV2VFe+lD+rcgiViIcw==,type:str]
mysqlRootPassword: ENC[AES256_GCM,data:t+Gr2a3a4UU23jY=,iv:rJHsEoFJCWwC4LJmsnNTV/v7AGfse47SEfvmthGONCE=,tag:e+FRZoLZ0vZ4KwmamiKoBA==,type:str]
mysqlDefaultSvoeDb: ENC[AES256_GCM,data:aVPricoNsA==,iv:CcUgpw8UU5Fca+FGURl6/oZrlBcDCu47kyOGn9VC+G0=,tag:2wYGZUFF95uyGN0Ne+vnBg==,type:str]
mysqlRootUsername: ENC[AES256_GCM,data:6Atlq+XcV+n5,iv:1gTW/8vmshPgQj/7VvTfkkQdJB0sn9iXhJg0jY1cCcc=,tag:WkLwu8ReevWDZrbCcMBrgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1krdwnh00t6u9ldsemglfg9wdvjuhws4zq67c596uf2tafzy0h5jsnk9rwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJK1hnNkRIZTBUYmZSZldM
            U1ZqL05kSUpkTFZvRWd5RkpZWEVoN1V6ZjI0Clg4STlJUUJQWWVnWDFsYzZHbTBC
            UkxEQzhLTjZtMVpwelNTMFNMRm02ZmsKLS0tIHFvbDFxZDh6VmZwNVUwOGtPK3k3
            OERMNFBmbTBHZlhPU3IvYlhiV25sOW8K6FbhUG+sdHtlfYirCDv5n20BvkeQn+bo
            IZDGb2P6V7NhKnoA8zt2eXnXgEN9ksuCA8TVgAVFO2JI0QH9Yh10rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-10T13:53:20Z"
    mac: ENC[AES256_GCM,data:kF4JIRUIfvFMQkfm+5FJ7yHm3rOYz/lM/sf1HX4IyEb4fIE6LOMNpGZNAzBU8t/xkgKqR94dmPtaJdTb4Ckf185UlsBp+K8AmGVtaLJ0ebCAS8pKyY22/QCZ+gB36uvTSUqHqjTP4nLtpNTd52knCtM8grMhvrsjqRmlL/yWdTg=,iv:3N3momUT6gp2te3+5sezAA9nEiU0Dtb5AyV4tiAiguE=,tag:e6vgicInKK8iWXMQFPhZKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
