# TODO split into dev and prod
route:
  receiver: 'alertmanager_telegram_bot'

receivers:
  - name: 'alertmanager_telegram_bot'
    webhook_configs:
      - send_resolved: true
        url: 'http://alertmanager_telegram_bot:8081'