apiVersion: v1
kind: Service
metadata:
  name: svoe-test-stateful-set-svc
  labels:
    name: svoe-test-stateful-set-svc
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
  selector:
    name: svoe-test-stateful-set
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: svoe-test-stateful-set
  labels:
    name: svoe-test-stateful-set
spec:
  serviceName: svoe-test-stateful-set-svc
  replicas: 35
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      name: svoe-test-stateful-set
  template:
    metadata:
      labels:
        name: svoe-test-stateful-set
    spec:
      containers:
        - name: svoe-test-stateful-set-container
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - echo "Starting statefulset pod"; cat /etc/app/conf/set.conf; while true; do sleep 600; done
          volumeMounts:
            #        - name: data-vol
            #          mountPath: /app/data
            - name: conf-vol
              mountPath: /etc/app/conf
      initContainers:
        - name: init-svoe-test-stateful-set
          image: busybox
          command:
            - /mnt/scripts/run.sh
          volumeMounts:
            - name: scripts-vol
              mountPath: /mnt/scripts
            - name: conf-vol
              mountPath: /mnt/data
      volumes:
        - name: scripts-vol
          configMap:
            name: svoe-test-ss-conf-map
            defaultMode: 0555
        - name: conf-vol
          emptyDir: {}
#  volumeClaimTemplates:
#  - metadata:
#      name: data-vol
#    spec:
#      accessModes:
#        - ReadWriteOnce
#      resources:
#        requests:
#          storage: 1Gi
#      storageClassName: default