apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-feed-servicemonitor
  labels:
    name: data-feed-servicemonitor
spec:
  selector:
    matchLabels:
      monitored-by: data-feed-servicemonitor
  namespaceSelector:
    matchNames:
      - data-feed
  endpoints:
    - port: redis-metrics
      interval: 5s # TODO figure out interval?
    - port: df-metrics
      interval: 5s