apiVersion: v1
kind: Secret
metadata:
  name: data-feed-common-secret
type: Opaque
stringData:
  MYSQL_HOST: {{ .Values.commonSecrets.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.commonSecrets.mysql.port | quote }}
  MYSQL_DATABASE: {{ .Values.commonSecrets.mysql.database | quote }}
  MYSQL_USER: {{ .Values.commonSecrets.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.commonSecrets.mysql.password | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.commonSecrets.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.commonSecrets.s3.secretAccessKey | quote }}
  AWS_REGION: {{ .Values.commonSecrets.s3.region | quote }}