{{ if .Values.isMysqlHost }}
apiVersion: v1
kind: Secret
metadata:
  name: svoe-mysql-secret
type: Opaque
stringData:
  ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  DATABASE: {{ .Values.mysql.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: svoe-mysql-backup-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  AWS_REGION: {{ .Values.s3.region | quote }}
{{ end }}